### ISSUE TITLE
MissingPropertyException: No such property: getGoogleResource  for OAuthService

### ISSUE THREAD

**Issue by pearlsravanthi** [donbeave/grails-spring-security-oauth-google#4]
Hi,

Am using  0.3.1 version of this plugin. On successful authentication, missing property exception is getting thrown for getGoogleResource instead of invoking methodMissing. Stacktrace for this action is as follows. Please suggest me what is going wrong here.

<pre>
Caused by: groovy.lang.MissingPropertyException: No such property: getGoogleResource for class: uk.co.desirableobjects.oauth.scribe.OauthService
	at GrailsMelodyGrailsPlugin$_closure4_closure16_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:162)
	at grails.plugin.springsecurity.oauth.GoogleSpringSecurityOAuthService.createAuthToken(GoogleSpringSecurityOAuthService.groovy:33)
	at GrailsMelodyGrailsPlugin$_closure4_closure16_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)
	at species.auth.SpringSecurityOAuthController.createAuthToken(SpringSecurityOAuthController.groovy:185)
	at species.auth.SpringSecurityOAuthController$_closure1.doCall(SpringSecurityOAuthController.groovy:67)
	... 15 more
</pre>

**Comment by pearlsravanthi** [comment]
Found the cause for this exception. This was happening because of grails-melody plugin. Tried disabling this plugin and every thing seemed ok. thanku
